FROM python:3.11-slim

RUN apt-get update && apt-get install -y \
    gcc \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
COPY deploy_redis.py .
COPY .env .

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5500

ENV HOST=0.0.0.0
ENV PORT=5500
ENV WORKERS=2

CMD aquiles-rag deploy --host ${HOST} --port ${PORT} --workers ${WORKERS} deploy_redis.py